<?php

/**
 * @file
 * Contains colour_hex_code.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function colour_hex_code_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the colour_hex_code module.
    case 'help.page.colour_hex_code':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a FieldWidget plugin for adding colour hex codes into a form display') . '</p>';
      return $output;

    default:
  }
}
