version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: <MYSQL_ROOT_PASSWORD>
    volumes:
      - db_data:/var/lib/mysql
      - ./db-backups:/var/lib/mysql/backups
    restart: always
  solr:
    image: wodby/solr:7.7
    environment:
      SOLR_DEFAULT_CONFIG_SET: solr_7.x_config
    ports:
      - "8983:8983"
    volumes:
      - ./docker/solr/create-cores.sh:/docker-entrypoint-initdb.d/create-cores.sh
      # Use the config set from client deploy config
      - ./config/solr/Elects:/opt/docker-solr/configsets/solr_7.x_config
  web:
    depends_on:
      - db
      - solr
    build: ./docker/web
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - .:/var/www/html
    env_file:
        - .env
  redis:
    image: redis:4.0.9
    ports:
      - "6379:6379"
volumes:
  db_data:
