<?php

/**
 * @file
 * Contains user_messages.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_messages_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_messages module.
    case 'help.page.user_messages':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User messages') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_messages_theme() {
  $theme = [];
  $theme['user_messages'] = [
    'render element' => 'children',
  ];
  $theme['user_message'] = [
    'render element' => 'elements',
    'file' => 'user_message.page.inc',
    'template' => 'user_message',
  ];
  $theme['user_message_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'user_message.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function user_messages_theme_suggestions_user_message(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#user_message'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'user_message__' . $sanitized_view_mode;
  $suggestions[] = 'user_message__' . $entity->bundle();
  $suggestions[] = 'user_message__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'user_message__' . $entity->id();
  $suggestions[] = 'user_message__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
