<?php

/**
 * @file
 * Contains descendants_menu_block.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function descendants_menu_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the descendants_menu_block module.
    case 'help.page.descendants_menu_block':
      $text = file_get_contents(dirname(__FILE__) . "/README.md");
      if (! \Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      } else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = array('settings' => $settings);
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }

  return NULL;

}
